const userRoutes = {
  signUp: "user/signup",
  verifyOTP: "user/verifyOtp",
  resendOtp: "user/resendOtp",
  login: "user/login",
  logout: "user/logout",
  forgotPassword: "user/forgotPassword",
  forgotVerify: "user/forgotVerify",
  changeStatus: "user/changeStatus",
  getUserInfo: "user/getUser",
  changeUserName: "user/changeUserName",
  changeDisplayName: "user/changeDisplayName",
  changePassword: "user/changePassword",
  changeProfile: "user/changeProfile",
  getGlobalFriends: "user/getGlobalFriends",
  addFriend: "user/addFriend",
  getFriends: "user/getFriends",
  sendMessage: "user/sendMessage",
  getAllUsers: "user/getAllUsers",
  removeFriend: "user/removeFriend",
  createCommuity: "user/createCommunity",
  getCommunities: "user/getCommunities",
  getMyCommunity: "user/getMyCommunity",
  joinCommunity: "user/joinCommunity",
  leaveCommunity: "user/leaveCommunity",
  getMembers: "user/getMembers",
};

export default userRoutes;
