const userRoutes = {
  signUp: "user/signup",
  verifyOTP: "user/verifyOtp",
  resendOtp: "user/resendOtp",
  login: "user/login",
  logout: "user/logout",
  forgotPassword: "user/forgotPassword",
  forgotVerify: "user/forgotVerify",
  changeStatus: "user/changeStatus",
  getUserInfo: "user/getUser",
  changeUserName: "user/changeUserName",
  changeDisplayName: "user/changeDisplayName",
  changePassword: "user/changePassword",
  changeProfile: "user/changeProfile",
  getGlobalFriends: "user/getGlobalFriends",
  addFriend: "user/addFriend",
  getFriends: "user/getFriends",
  sendMessage: "user/sendMessage",
  fetchMessages: "user/fetchMessages",
  getAllUsers: "user/getAllUsers",
  removeFriend: "user/removeFriend",
  createCommuity: "user/createCommunity",
  getCommunities: "user/getCommunities",
  getMyCommunity: "user/getMyCommunity",
  getCommunityById: "user/getCommunityById",
  joinCommunity: "user/joinCommunity",
  leaveCommunity: "user/leaveCommunity",
  getMembers: "user/getMembers",
  getNotification: "user/getNotification",
  acceptFriendRequest: "user/acceptFriendRequest",
  rejectFriendRequest: "user/rejectFriendRequest",
  clearNotifications: "user/clearNotifications",
  newZepchat: "user/newZepchat",
  getZepchats: "user/getZepchats",
  postReply: "user/postReply",
  getReplies: "user/getReplies",
  getZepchatById: "user/getZepchatById",
  replyVote: "user/replyVote",
  voteZepchat: "user/voteZepchat",
  deleteZepchat: "user/deleteZepchat",
  updateZepchat: "user/updateZepchat",
  removeMember: "user/removeMember",
  updateCommunity: "user/updateCommunity  ",
  sendCommunityMessage: "user/sendCommunityMessage",
  getCommunityMessages: "user/getCommunityMessages",
  reportUser: "user/reportUser ",
  communityReport: "user/communityReport",
};

export default userRoutes;
